---
authors:
  - Ansible Network Community (ansible-network)
license_file: LICENSE
name: cli
namespace: network
readme: README.rst
repository: https://github.com/ansible-network/ansible_collections.network.cli
